# Generated by Django 4.0.4 on 2022-07-09 12:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_remove_comment_post_alter_comment_entity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='entity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='network.entity'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 9, 12, 24, 22, 769453)),
        ),
        migrations.AlterField(
            model_name='post',
            name='entity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='network.entity'),
        ),
    ]
