# Generated by Django 4.0.4 on 2022-08-06 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_comment_entity_alter_entity_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pfp',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 6, 8, 46, 24, 648620)),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
