# Generated by Django 4.0.4 on 2022-08-09 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_remove_comment_user_alter_entity_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 9, 10, 6, 15, 315329)),
        ),
        migrations.AlterField(
            model_name='user',
            name='pfp',
            field=models.ImageField(default='static/profile-icon.jpg', null=True, upload_to='images/'),
        ),
    ]
