# Generated by Django 4.0.4 on 2022-08-09 10:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_alter_entity_date_alter_user_pfp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 9, 10, 11, 9, 659687)),
        ),
        migrations.AlterField(
            model_name='user',
            name='pfp',
            field=models.ImageField(default='/images/profile-icon.jpg', null=True, upload_to='images/'),
        ),
    ]
