# Generated by Django 4.0.4 on 2022-08-09 21:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_alter_entity_date_alter_user_pfp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='biography',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='cover',
            field=models.TextField(default='#707070'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 9, 21, 14, 39, 201680)),
        ),
    ]
